name: real_estate_app
description: Application immobiliÃ¨re Flutter avec Appwrite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.6.1
  
  # Appwrite SDK
  appwrite: ^20.3.0
  flutter_web_auth_2: ^4.1.0
  
  # Navigation
  go_router: ^13.0.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  
  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.0.9
  
  # Images & Media
  image_picker: ^1.0.5
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  
  # Utilities
  uuid: ^4.3.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  
  # HTTP & Networking
  http: ^1.1.2
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Forms & Input
  flutter_rating_bar: ^4.0.1
  
  # Realtime & WebSockets
  web_socket_channel: ^3.0.3
  
  # UI Enhancements
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Animations
  animations: ^2.0.11
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
  
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
